name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov  # Install pytest-cov to collect coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with pytest --pylint
      run: |
        pytest --cov=app --cov-report=term-missing  # Collect coverage for the app directory and show missing lines

    - name: Lint with flake8
      run: |
        flake8 .  # Run flake8 linting to check for code style issues
